# docker/grafana/datasources/prometheus.yml
apiVersion: 1

datasources:
  - name:      Prometheus
    type:      prometheus
    access:    proxy

    # Grafana reaches Prometheus through the Docker network
    url: http://prometheus:9090

    isDefault: true
    editable:  true